name: dart_polymer_date_picker_demo
description: A web app that uses AngularDart Components
version: 0.0.1
#homepage: https://www.example.com
#author: EmersonMoura <email@example.com>

environment:
  sdk: '>=1.23.0 <2.0.0'

dependencies:
  angular2: ^3.0.0
  angular_components: ^0.5.0
  polymer: "^1.0.0-rc"
  polymer_elements: "^1.0.0-rc"
  web_components: ^0.12.0
  dart_polymer_date_picker:
    path: polymer-date-picker
dev_dependencies:
  browser: ^0.10.0
  dart_to_js_script_rewriter: ^1.0.1

transformers:
- polymer:
    entry_points:
      - web/index.html
- angular2:
    platform_directives:
    - 'package:angular2/common.dart#COMMON_DIRECTIVES'
    platform_pipes:
    - 'package:angular2/common.dart#COMMON_PIPES'
    entry_points: web/main.dart
- dart_to_js_script_rewriter
